#
# Copyright SecureKey Technologies Inc. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#
#
# The network connection profile provides client applications the information about the target
# blockchain network that are necessary for the applications to interact with it. These are all
# knowledge that must be acquired from out-of-band sources. This file provides such a source.
#


#
# Schema version of the content. Used by the SDK to apply the corresponding parsing rules.
#
version: 1.0.0

#
# The client section used by GO SDK.
#
client:

  # Which organization does this application instance belong to? The value must be the name of an org
  # defined under "organizations"
  organization: org1

  logging:
    level: info

  # Root of the MSP directories with keys and certs.
  cryptoconfig:
    path: ${GOPATH}/src/github.com/swetharepakula/evm-workshop/fabric-cluster

  # Some SDKs support pluggable KV stores, the properties under "credentialStore"
  # are implementation specific
  credentialStore:
  #   # [Optional]. Used by user store. Not needed if all credentials are embedded in configuration
  #   # and enrollments are performed elswhere.
    path: "/tmp/state-store"

    # [Optional]. Specific to the CryptoSuite implementation used by GO SDK. Software-based implementations
    # requiring a key store. PKCS#11 based implementations does not.
    cryptoStore:
      # Specific to the underlying KeyValueStore that backs the crypto key store.
      path: /tmp/msp

   # BCCSP config for the client. Used by GO SDK.
  BCCSP:
    security:
     enabled: true
     default:
      provider: "SW"
     hashAlgorithm: "SHA2"
     softVerify: true
     level: 256

  tlsCerts:
    # [Optional]. Use system certificate pool when connecting to peers, orderers (for negotiating TLS) Default: false
    systemCertPool: true

#
# [Optional]. But most apps would have this section so that channel objects can be constructed
# based on the content below. If an app is creating channels, then it likely will not need this
# section.
#
channels:
  # name of the channel
  channela:
    # Required. list of orderers designated by the application to use for transactions on this
    # channel. This list can be a result of access control ("org1" can only access "ordererA"), or
    # operational decisions to share loads from applications among the orderers.  The values must
    # be "names" of orgs defined under "organizations/peers"
    # deprecated: not recommended, to override any orderer configuration items, entity matchers should be used.
#    orderers:
#      - orderer.example.com

    # Required. list of peers from participating orgs
    peers:
      blockchain-org1peer0.org1.example.com:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true
      blockchain-org2peer0.org2.example.com:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true

    # [Optional]. The application can use these options to perform channel operations like retrieving channel
    # config etc.
    policies:
      #[Optional] options for retrieving channel configuration blocks
      queryChannelConfig:
        #[Optional] min number of success responses (from targets/peers)
        minResponses: 1
        #[Optional] channel config will be retrieved for these number of random targets
        maxTargets: 1
        #[Optional] retry options for query config block
        retryOpts:
          #[Optional] number of retry attempts
          attempts: 5
          #[Optional] the back off interval for the first retry attempt
          initialBackoff: 500ms
          #[Optional] the maximum back off interval for any retry attempt
          maxBackoff: 5s
          #[Optional] he factor by which the initial back off period is exponentially incremented
          backoffFactor: 2.0
  channelc:
    # Required. list of orderers designated by the application to use for transactions on this
    # channel. This list can be a result of access control ("org1" can only access "ordererA"), or
    # operational decisions to share loads from applications among the orderers.  The values must
    # be "names" of orgs defined under "organizations/peers"
    # deprecated: not recommended, to override any orderer configuration items, entity matchers should be used.
#    orderers:
#      - orderer.example.com

    # Required. list of peers from participating orgs
    peers:
      blockchain-org1peer0.org1.example.com:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true
      blockchain-org2peer0.org2.example.com:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true
      blockchain-org3peer0.org3.example.com:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true
      blockchain-org4peer0.org4.example.com:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true

    # [Optional]. The application can use these options to perform channel operations like retrieving channel
    # config etc.
    policies:
      #[Optional] options for retrieving channel configuration blocks
      queryChannelConfig:
        #[Optional] min number of success responses (from targets/peers)
        minResponses: 1
        #[Optional] channel config will be retrieved for these number of random targets
        maxTargets: 1
        #[Optional] retry options for query config block
        retryOpts:
          #[Optional] number of retry attempts
          attempts: 5
          #[Optional] the back off interval for the first retry attempt
          initialBackoff: 500ms
          #[Optional] the maximum back off interval for any retry attempt
          maxBackoff: 5s
          #[Optional] he factor by which the initial back off period is exponentially incremented
          backoffFactor: 2.0

#
# list of participating organizations in this network
#
organizations:
  org1:
    mspid: Org1MSP
    cryptoPath:  peerOrganizations/org1.example.com/users/{username}@org1.example.com/msp
    peers:
      - blockchain-org1peer0.org1.example.com
    certificateAuthorities:

  org2:
    mspid: Org2MSP
    cryptoPath:  peerOrganizations/org2.example.com/users/{username}@org2.example.com/msp
    peers:
      - blockchain-org2peer0.org2.example.com
    certificateAuthorities:

  org3:
    mspid: Org3MSP
    cryptoPath:  peerOrganizations/org3.example.com/users/{username}@org3.example.com/msp
    peers:
      - blockchain-org3peer0.org3.example.com
    certificateAuthorities:

  org4:
    mspid: Org4MSP
    cryptoPath:  peerOrganizations/org4.example.com/users/{username}@org4.example.com/msp
    peers:
      - blockchain-org4peer0.org4.example.com
    certificateAuthorities:
  # the profile will contain public information about organizations other than the one it belongs to.
  # These are necessary information to make transaction lifecycles work, including MSP IDs and
  # peers with a public URL to send transaction proposals. The file will not contain private
  # information reserved for members of the organization, such as admin key and certificate,
  # fabric-ca registrar enroll ID and secret, etc.
  # Orderer Org name
  ordererorg:
      mspID: OrdererMSP
      cryptoPath: ordererOrganizations/example.com/users/{username}@example.com/msp


#
# List of orderers to send transaction and channel create/update requests to. For the time
# being only one orderer is needed. If more than one is defined, which one get used by the
# SDK is implementation specific. Consult each SDK's documentation for its handling of orderers.
#
orderers:
  blockhain-orderer.example.com:
    url: blockchain-orderer.example.com:31010
    grpcOptions:
      ssl-target-name-override: blockchain-orderer.example.com
      keep-alive-time: 0s
      keep-alive-timeout: 20s
      keep-alive-permit: false
      fail-fast: false
      allow-insecure: false
    tlsCACerts:
      path: ${GOPATH}/src/github.com/swetharepakula/evm-workshop/fabric-cluster/ordererOrganizations/example.com/tlsca/tlsca.example.com-cert.pem

#
# List of peers to send various requests to, including endorsement, query
# and event listener registration.
#
peers:
  blockchain-org1peer0.org1.example.com:
    url: blockchain-org1peer0.org1.example.com:30110
    grpcOptions:
      ssl-target-name-override: blockchain-org1peer0.org1.example.com
      keep-alive-time: 0s
      keep-alive-timeout: 20s
      keep-alive-permit: false
      fail-fast: false
      allow-insecure: false
    tlsCACerts:
      path: ${GOPATH}/src/github.com/swetharepakula/evm-workshop/fabric-cluster/peerOrganizations/org1.example.com/tlsca/tlsca.org1.example.com-cert.pem
  blockchain-org2peer0.org2.example.com:
    url: blockchain-org2peer0.org2.example.com:30210
    grpcOptions:
      ssl-target-name-override: blockchain-org2peer0.org2.example.com
      keep-alive-time: 0s
      keep-alive-timeout: 20s
      keep-alive-permit: false
      fail-fast: false
      allow-insecure: false
    tlsCACerts:
      path: ${GOPATH}/src/github.com/swetharepakula/evm-workshop/fabric-cluster/peerOrganizations/org2.example.com/tlsca/tlsca.org2.example.com-cert.pem
  blockchain-org3peer0.org3.example.com:
    url: blockchain-org3peer0.org3.example.com:30310
    grpcOptions:
      ssl-target-name-override: blockchain-org3peer0.org3.example.com
      keep-alive-time: 0s
      keep-alive-timeout: 20s
      keep-alive-permit: false
      fail-fast: false
      allow-insecure: false
    tlsCACerts:
      path: ${GOPATH}/src/github.com/swetharepakula/evm-workshop/fabric-cluster/peerOrganizations/org3.example.com/tlsca/tlsca.org3.example.com-cert.pem
  blockchain-org4peer0.org4.example.com:
    url: blockchain-org4peer0.org4.example.com:30410
    grpcOptions:
      ssl-target-name-override: blockchain-org4peer0.org4.example.com
      keep-alive-time: 0s
      keep-alive-timeout: 20s
      keep-alive-permit: false
      fail-fast: false
      allow-insecure: false
    tlsCACerts:
      path: ${GOPATH}/src/github.com/swetharepakula/evm-workshop/fabric-cluster/peerOrganizations/org4.example.com/tlsca/tlsca.org4.example.com-cert.pem

entityMatchers:
  peer:
    - pattern: blockchain-org1peer0.org1.example.(\w+)
      urlSubstitutionExp: <cluster-ip>:30110
      sslTargetOverrideUrlSubstitutionExp: blockchain-org1peer0.org1.example.com
      mappedHost: blockchain-org1peer0.org1.example.com

    - pattern: blockchain-org2peer0.org2.example.(\w+)
      urlSubstitutionExp: <cluster-ip>:30210
      sslTargetOverrideUrlSubstitutionExp: blockchain-org2peer0.org2.example.com
      mappedHost: blockchain-org2peer0.org2.example.com

    - pattern: blockchain-org3peer0.org3.example.(\w+)
      urlSubstitutionExp: <cluster-ip>:30310
      sslTargetOverrideUrlSubstitutionExp: blockchain-org3peer0.org3.example.com
      mappedHost: blockchain-org3peer0.org3.example.com

    - pattern: blockchain-org4peer0.org4.example.(\w+)
      urlSubstitutionExp: <cluster-ip>:30410
      sslTargetOverrideUrlSubstitutionExp: blockchain-org4peer0.org4.example.com
      mappedHost: blockchain-org4peer0.org4.example.com

    - pattern: (\w+).org1.example.(\w+):(\d+)
      urlSubstitutionExp: <cluster-ip>:$2
      sslTargetOverrideUrlSubstitutionExp: $1.org1.example.com
      mappedHost: $1.org1.example.com

    - pattern: (\w+).org2.example.(\w+):(\d+)
      urlSubstitutionExp: <cluster-ip>:$2
      sslTargetOverrideUrlSubstitutionExp: $1.org2.example.com
      mappedHost: $1.org2.example.com

    - pattern: (\w+).org3.example.(\w+):(\d+)
      urlSubstitutionExp: <cluster-ip>:$2
      sslTargetOverrideUrlSubstitutionExp: $1.org3.example.com
      mappedHost: $1.org3.example.com

    - pattern: (\w+).org4.example.(\w+):(\d+)
      urlSubstitutionExp: <cluster-ip>:$2
      sslTargetOverrideUrlSubstitutionExp: $1.org4.example.com
      mappedHost: $1.org4.example.com

    - pattern: (\w+):30110
      urlSubstitutionExp: <cluster-ip>:30110
      sslTargetOverrideUrlSubstitutionExp: blockchain-org1peer0.org1.example.com
      mappedHost: blockchain-org1peer0.org1.example.com

    - pattern: (\w+):30210
      urlSubstitutionExp: <cluster-ip>:30210
      sslTargetOverrideUrlSubstitutionExp: blockchain-org2peer0.org2.example.com
      mappedHost: blockchain-org2peer0.org2.example.com

    - pattern: (\w+):30310
      urlSubstitutionExp: <cluster-ip>:30310
      sslTargetOverrideUrlSubstitutionExp: blockchain-org3peer0.org3.example.com
      mappedHost: blockchain-org3peer0.org3.example.com

    - pattern: (\w+):30410
      urlSubstitutionExp: <cluster-ip>:30410
      sslTargetOverrideUrlSubstitutionExp: blockchain-org4peer0.org4.example.com
      mappedHost: blockchain-org4peer0.org4.example.com

  orderer:

    - pattern: (\w+).example.(\w+)
      urlSubstitutionExp: <cluster-ip>:31010
      sslTargetOverrideUrlSubstitutionExp: blockchain-orderer.example.com
      mappedHost: blockchain-orderer.example.com

    - pattern: (\w+).example.(\w+):(\d+)
      urlSubstitutionExp: <cluster-ip>:31010
      sslTargetOverrideUrlSubstitutionExp: blockchain-orderer.example.com
      mappedHost: blockhain-orderer.example.com

    - pattern: blockchain-orderer:31010
      urlSubstitutionExp: <cluster-ip>:31010
      sslTargetOverrideUrlSubstitutionExp: blockchain-orderer.example.com
      mappedHost: blockhain-orderer.example.com
